import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, Lock, AlertTriangle, ChevronRight, CheckCircle2 } from 'lucide-react';

export default function Onboarding({ onComplete }) {
  const [step, setStep] = useState(0);

  const steps = [
    {
      title: "Welcome to SolasCare Pro",
      icon: Shield,
      color: "text-brand-violet",
      bg: "bg-brand-violet/20",
      content: (
        <div className="space-y-4 text-slate-300">
          <p>
            You're one step away from a faster, cleaner, and more reliable PC. 
            SolasCare Pro provides enterprise-grade diagnostics, driver management, 
            and deep-system repair tools in one intuitive interface.
          </p>
          <ul className="space-y-2 mt-4 text-sm">
            <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400"/> No bundled bloatware or ads.</li>
            <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400"/> Transparent "Dry-Run" previews.</li>
            <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400"/> Automatic Restore Points before deep fixes.</li>
          </ul>
        </div>
      )
    },
    {
      title: "Our Privacy Promise",
      icon: Lock,
      color: "text-brand-cyan",
      bg: "bg-brand-cyan/20",
      content: (
        <div className="space-y-4 text-slate-300">
          <p>
            Your trust is our top priority. We believe your system data belongs to you.
          </p>
          <div className="p-4 bg-slate-900 rounded border border-brand-border/50 text-sm">
            <p className="font-bold text-white mb-2">100% Local Execution</p>
            <p>
              SolasCare Pro operates entirely on your local machine. We do <strong>not</strong> collect, store, 
              or upload any personal telemetry, files, or usage metrics to our servers. 
              Logs generated by our tools remain strictly on your hard drive in your AppData folder.
            </p>
          </div>
        </div>
      )
    },
    {
      title: "Liability & EULA",
      icon: AlertTriangle,
      color: "text-amber-400",
      bg: "bg-amber-400/20",
      content: (
        <div className="space-y-4 text-slate-300">
          <p>
            Because SolasCare Pro interacts directly with your Windows Registry, Drivers, and Core Services, 
            it is powerful but carries inherent risks.
          </p>
          <div className="p-4 bg-amber-950/20 rounded border border-amber-500/30 text-sm">
            <p className="font-bold text-amber-400 mb-2">Use at your own risk</p>
            <p>
              By proceeding, you acknowledge that you are using these tools at your own risk. 
              While we include safeguards like Restore Points, the developers assume no liability 
              for data loss, system instability, or hardware failure resulting from the use of this software.
            </p>
          </div>
        </div>
      )
    }
  ];

  const handleNext = () => {
    if (step < steps.length - 1) {
      setStep(step + 1);
    } else {
      localStorage.setItem('solas_onboarded', 'true');
      onComplete();
    }
  };

  const CurrentIcon = steps[step].icon;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-brand-navy/95 backdrop-blur-sm p-4">
      <motion.div 
        key="onboarding-modal"
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        className="glass-panel w-full max-w-xl overflow-hidden shadow-2xl shadow-brand-violet/10 flex flex-col"
      >
        <div className="p-8 flex-1">
          <div className="flex items-center gap-4 mb-6">
            <div className={`p-3 rounded-xl ${steps[step].bg}`}>
              <CurrentIcon className={`w-8 h-8 ${steps[step].color}`} />
            </div>
            <h2 className="text-2xl font-bold text-white">{steps[step].title}</h2>
          </div>
          
          <div className="min-h-[180px]">
            <AnimatePresence mode="wait">
              <motion.div
                key={step}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.2 }}
              >
                {steps[step].content}
              </motion.div>
            </AnimatePresence>
          </div>
        </div>

        <div className="bg-slate-900/50 p-6 border-t border-brand-border flex items-center justify-between">
          <div className="flex gap-2">
            {steps.map((_, i) => (
              <div 
                key={i} 
                className={`h-1.5 rounded-full transition-all duration-300 ${i === step ? 'w-8 bg-brand-violet' : i < step ? 'w-4 bg-brand-violet/50' : 'w-4 bg-slate-700'}`}
              />
            ))}
          </div>
          <button 
            onClick={handleNext}
            className="flex items-center gap-2 px-6 py-2.5 bg-brand-violet hover:bg-brand-violet/80 text-white font-bold rounded-lg transition-colors cursor-pointer"
          >
            {step === steps.length - 1 ? 'Accept & Continue' : 'Next'}
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
      </motion.div>
    </div>
  );
}
